apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-cruise-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: research-cruise-app-frontend
  template:
    metadata:
      labels:
        app: research-cruise-app-frontend
    spec:
      containers:
        - name: research-cruise-app-frontend
          image: research-cruise-app-frontend
          env:
            - name: API_URL
              value: http://research-cruise-app-backend:8080/
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
