apiVersion: v1
kind: Service
metadata:
  name: research-cruise-app-frontend
spec:
  selector:
    app: research-cruise-app-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
