services:
  backend:
    container_name: researchcruiseapp-backend
    build:
      context: ../backend
    environment:
      - Database__SeedAutomatically=false
      - Database__MigrateAutomatically=false
      - Database__LogUserPasswordsWhenSeeding=false
      - ConnectionStrings__Database=Server=db,1433;Database=ResearchCruiseApp;User Id=sa;Password=p@ssw0rd;Encrypt=False
    ports:
      - 3000:8080
    depends_on:
      - db
  frontend:
    container_name: researchcruiseapp-frontend
    build:
      context: ../frontend
    ports:
      - 8080:80