name: Format & lint checks

on:
  push:
    paths-ignore:
      - docs

jobs:
  frontend-checks:
    name: Frontend checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10"
          package_json_file: frontend/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run eslint

      - name: Check formatting
        run: pnpm run prettier

  backend-checks:
    name: Backend checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Check formatting
        run: dotnet csharpier --check .
